[local]
basepath= "c:\\erve-online"
out="out"
in="in"
tmp="tmp"
backup="backup"
customers="Customers"
inventory="Inventory"
items="Items"
salesorders="SalesOrders"
[cloud]
basepath="/ErveOnline_TEST"
erpout="erpout"
cmsout="cmsout"
tmp="tmp"
customers="Customers"
inventory="Inventory"
items="Items"
salesorders="SalesOrders"
username="support@erve.shop"
password="WebErve365!"